---
- name: Start new VirtualBox VMs
  environment:
    DISPLAY: "localhost:1"
  block:
    - name: Restart vncserver
      command: vncserver

    - name: Add xhost
      command: xhost +

    - name: Supress GUI VBox messages
      shell: 'VBoxManage setextradata global GUI/SuppressMessages remindAboutAutoCapture,remindAboutWrongColorDepth,remindAboutMouseIntegrationOn,remindAboutMouseIntegrationOff,confirmInputCapture,confirmGoingFullscreen'

    - name: Add VRAM and RAM on Workstation
      shell: 'VBoxManage modifyvm Whonix-Workstation-XFCE --vram 128 --memory 4096'

    - name: Add RAM on Gateway
      shell: 'VBoxManage modifyvm Whonix-Gateway-XFCE --memory 4096'

    - name: Start gateway VM
      shell: "VBoxManage startvm Whonix-Gateway-XFCE"

    - name: Start workstation VM
      shell: "VBoxManage startvm Whonix-Workstation-XFCE"

    - name: Wait for VMs to boot and connect to TOR
      pause:
        minutes: 3
